Repository callMe-Dev/git-guide, pull requests merged in 2021-03, with the labels that each got.

#17 Mac os
  src/components/InstallMacOs/InstallMacos.jsx
  src/components/InstallMacOs/InstallMacos.scss
  src/components/_index.scss
  src/views/Layout/Layout.jsx
Labels: features

#18 Creé la vista de Gitlab
  src/assets/gitLabAssets/create-project-gitlab.png
  src/assets/gitLabAssets/form-gitlab.png
  src/assets/gitLabAssets/repository-gitlab.png
  src/components/GitLab/GitLab.jsx
  src/components/GitLab/GitLab.scss
  src/components/MenuMobile/MenuContent/CommandsContainer.jsx
  src/components/_index.scss
  src/views/Layout/Layout.jsx
Labels: features

#20 Change componts to views
  public/index.html
  src/components/CommandsContainer/CommandName/CommandName.jsx
  src/components/CommandsContainer/CommandsContainer.jsx
  src/components/CommandsContainer/commands/GitInit/GitInit.jsx
  src/components/CommandsContainer/commands/README.md
  src/components/ContentComponent/ContentComponent.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/MenuMobile/Commands/CommandsContainer.scss
  src/components/MenuMobile/MenuMobile.jsx
  src/components/Repositories/GitLab/GitLab.jsx
  src/components/_index.scss
  src/index.scss
  src/views/ContentHome/ContentHome.jsx
  src/views/ContentHome/ContentHome.scss
  src/views/GitConfigView/GitConfigView.jsx
  src/views/GitConfigView/GitConfigView.scss
  src/views/GitConfigView/configManual/configManual.jsx
  src/views/GitConfigView/configTerminal/configTerminal.jsx
  src/views/GitConfigView/editorConfig/editorConfig.jsx
  src/views/GitConfigView/editorConfig/editorConfigContent.jsx
  src/views/GitConfigView/knowConfig/knowConfig.jsx
  src/views/Layout/Layout.jsx
  src/views/SideBar/SideBar.jsx
  src/views/_views.scss
  src/views/os_views/InstallLinux/InstallLinux.jsx
  src/views/os_views/InstallLinux/InstallLinux.scss
  src/views/os_views/InstallLinux/distros/arch/arch.jsx
  src/views/os_views/InstallLinux/distros/centOs/centOs.jsx
  src/views/os_views/InstallLinux/distros/debian/debian.jsx
  src/views/os_views/InstallLinux/distros/fedora/fedora.jsx
  src/views/os_views/InstallLinux/distros/gentoo/gentoo.jsx
  src/views/os_views/InstallLinux/distros/others/others.jsx
  src/views/os_views/InstallMacOs/InstallMacos.jsx
  src/views/os_views/InstallMacOs/InstallMacos.scss
  src/views/os_views/InstallWindows/InstallWindows.jsx
  src/views/os_views/InstallWindows/installWindows.scss
Labels: bug fixed, features

#21 Test json commands
  src/components/CommandsContainer/CommandName/CommandName.jsx
  src/components/CommandsContainer/CommandsContainer.jsx
  src/components/CommandsContainer/CommandsContainer.scss
  src/components/CommandsContainer/README.md
  src/components/CommandsContainer/commands/GitInit/GitInit.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.scss
  src/components/CommandsContainer/commands/README.md
  src/components/CommandsContainer/commands/commands.json
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/_index.scss
  src/scss/global/_globals.scss
  src/views/Layout/Layout.jsx
  src/views/Layout/Layout.scss
  src/views/Layout/Routes/Routes.jsx
Labels: bug fixed, documentation, features

#22 feat: cree el component de LazyLoading para las Img
  src/components/BtnToTop/BtnToTop.jsx
  src/components/LazyImg/LazyImg.jsx
  src/components/Logo/Logo.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/NavMobile/NavMobile.jsx
  src/components/Repositories/GitHub/Github.jsx
  src/components/Repositories/GitLab/GitLab.jsx
  src/views/Layout/Layout.jsx
  src/views/os_views/InstallWindows/InstallWindows.jsx
Labels: features

#23 Test react helmet
  package-lock.json
  package.json
  public/index.html
  src/components/AnchorTag/AnchorTag.jsx
  src/components/ButtonShowInfo/ButtonShowInfo.jsx
  src/components/CommandsContainer/CommandName/CommandName.jsx
  src/components/CommandsContainer/CommandsContainer.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.jsx
  src/components/ImportantNote/ImportantNote.jsx
  src/components/LazyImg/LazyImg.jsx
  src/components/Logo/Logo.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/MenuMobile/MenuMobile.jsx
  src/components/MetaHelmet/MetaHelmet.jsx
  src/components/NavMobile/NavMobile.jsx
  src/components/Repositories/GitLab/GitLab.scss
  src/components/_index.scss
  src/views/ContentHome/ContentHome.jsx
  src/views/GitConfigView/GitConfigView.jsx
  src/views/Layout/Routes/Routes.jsx
  src/views/Repositories/GitHub/Github.jsx
  src/views/Repositories/GitIgnore.jsx
  src/views/Repositories/GitLab/GitLab.jsx
  src/views/Repositories/Repository.scss
  src/views/SideBar/SideBar.jsx
  src/views/_views.scss
  src/views/os_views/InstallLinux/InstallLinux.jsx
  src/views/os_views/InstallMacOs/InstallMacos.jsx
  src/views/os_views/InstallWindows/InstallWindows.jsx
Labels: documentation, features

#24 Add hover effects
  .gitignore
  src/components/BtnToTop/BtnToTop.scss
  src/components/ButtonShowInfo/ButtonShowInfo.scss
  src/components/CommandsContainer/commands/ListCommands/ListCommands.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.scss
  src/components/ImportantNote/ImportantNote.scss
  src/components/MenuMobile/Commands/CommandsContainer.scss
  src/index.scss
  src/scss/global/_globals.scss
  src/scss/mixins/_scaleHover.scss
  src/scss/mixins/_shadowHover.scss
  src/views/SideBar/SideBar.scss
Labels: features

#25 feat: agregue algunos comandos basicos de git
  src/components/CommandsContainer/commands/ListCommands/ListCommands.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.scss
  src/components/CommandsContainer/commands/commands.html
  src/components/CommandsContainer/commands/commands.json
Labels: features

#26 Add commands info
  public/_redirects
  src/components/CommandsContainer/commands/commands.html
  src/components/CommandsContainer/commands/commands.json
Labels: bug fixed
