Repository callMe-Dev/git-guide, pull requests merged in 2021-04, with the labels that each got.

#27 style: Se corrigieron palabras mal escritas
  src/components/CommandsContainer/commands/commands.json
  src/views/ContentHome/ContentHome.jsx
  src/views/GitConfigView/editorConfig/editorConfigContent.jsx
  src/views/Repositories/GitHub/Github.jsx
  src/views/Repositories/GitLab/GitLab.jsx
  src/views/os_views/InstallWindows/InstallWindows.jsx
Labels: bug fixed

#29 Feat/props in components
  src/components/BtnToTop/BtnToTop.jsx
  src/components/ButtonShowInfo/ButtonShowInfo.jsx
  src/components/CommandsContainer/CommandName/CommandName.jsx
  src/components/CommandsContainer/CommandsContainer.jsx
  src/components/CommandsContainer/commands/ListCommands/ListCommands.jsx
  src/components/ImportantNote/ImportantNote.jsx
  src/components/LazyImg/LazyImg.jsx
  src/components/MenuMobile/Commands/BtnOs/CommandsBtnOs.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/MenuMobile/Commands/CommandsContainer/CommandsContainerOne.jsx
  src/components/MenuMobile/Commands/CommandsContainer/CommandsContainerTwo.jsx
  src/components/MenuMobile/Commands/CommandsContainerContent/CommandsContainerContent.jsx
  src/components/MenuMobile/MenuMobile.jsx
  src/components/NavMobile/NavMobile.jsx
  src/index.js
  src/views/GitConfigView/configTerminal/configTerminal.jsx
  src/views/Layout/Routes/Routes.jsx
  src/views/SideBar/SideBar.jsx
Labels: bug fixed, documentation

#30 Feat/tutorials view
  AUTHORS
  src/components/BtnToTop/BtnToTop.scss
  src/components/ButtonShowInfo/ButtonShowInfo.scss
  src/components/CommandsContainer/CommandsContainer.scss
  src/components/ImportantNote/ImportantNote.scss
  src/components/MenuMobile/Commands/Btns/CommandsBtnBlue.jsx
  src/components/MenuMobile/Commands/Btns/CommandsBtnOs.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/MenuMobile/Commands/CommandsContainer.scss
  src/components/MenuMobile/Commands/CommandsContainer/CommandsContainerOne.jsx
  src/components/MenuMobile/Commands/CommandsContainer/CommandsContainerTwo.jsx
  src/components/YtIframe/YtIframe.jsx
  src/scss/_root.scss
  src/scss/global/_globals.scss
  src/scss/mixins/_codeStyle.scss
  src/scss/mixins/_contentStyle.scss
  src/scss/mixins/_linkStyle.scss
  src/scss/mixins/_subTitle.scss
  src/scss/mixins/_titleStyle.scss
  src/scss/mixins/_underlineText.scss
  src/views/GitConfigView/GitConfigView.scss
  src/views/Layout/Routes/Routes.jsx
  src/views/Layout/Routes/routes.js
  src/views/SideBar/SideBar.scss
  src/views/Tutorials/Tutorials.jsx
  src/views/Tutorials/Tutorials.scss
  src/views/_views.scss
Labels: bug fixed, documentation, features

#31 Feat/bitbucket repo
  .eslintrc.json
  src/assets/bitbucket/create-project.png
  src/assets/bitbucket/create-repo.png
  src/components/MenuMobile/Commands/CommandsContainer/CommandsContainerTwo.jsx
  src/components/YtIframe/YtIframe.jsx
  src/scss/mixins/_codeStyle.scss
  src/views/Layout/Layout.jsx
  src/views/Repositories/Bitbucket/Bitbucket.jsx
  src/views/Repositories/GitHub/Github.jsx
  src/views/Repositories/GitLab/GitLab.jsx
  src/views/Repositories/Repository.scss
  src/views/Routes/Routes.jsx
  src/views/Routes/routes.js
Labels: features

#32 chore: agregado comando status y tutorial sobre git
  src/components/CommandsContainer/commands/commands.json
  src/views/Tutorials/Tutorials.jsx
Labels: features

#33 feat: Dark Mode agregado
  src/App.jsx
  src/assets/gitLogoDarkMobile.svg
  src/components/ImportantNote/ImportantNote.scss
  src/components/Logo/Logo.jsx
  src/components/MenuMobile/Commands/CommandsContainer.jsx
  src/components/MenuMobile/Commands/CommandsContainer.scss
  src/components/MenuMobile/Commands/DarkMode/DarkMode.jsx
  src/components/MenuMobile/Commands/DarkMode/DarkMode.scss
  src/components/MenuMobile/MenuMobile.jsx
  src/components/NavMobile/NavMobile.jsx
  src/components/_index.scss
  src/scss/_root.scss
  src/scss/global/_globals.scss
  src/scss/mixins/_contentStyle.scss
  src/scss/mixins/_linkStyle.scss
  src/views/Layout/Layout.jsx
  src/views/SideBar/SideBar.jsx
  src/views/SideBar/SideBar.scss
Labels: features
